### ISSUE TITLE
Discrepancy in cytokine network expression data sources

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/shiny-iatlas#155]
@heimannch wrote

Here it goes a csv file with the cases of different values of gene expression across two different sources. I kept all ParticipantBarcodes that had at least one case of mismatch. 
Each gene has two columns, and the source of the gene expression data is encoded as follows:
.x = gene expression data from shiny-iatlas repo object panimmune_data$im_expr_df
.y = gene expression data from file "GenExp_All_CKine_genes.tsv", from the cytokine-network-dev repo.
[expr_mismatched.csv.gz](https://github.com/CRI-iAtlas/shiny-iatlas/files/3799243/expr_mismatched.csv.gz)

**Comment by vthorsson** [comment]
First test case, BTLA gene , ParticipantBarcode TCGA-ZU-A8S4 has values 6.5879 and 4.4871 respectively for x and y
```
SELECT *
FROM `pancancer-atlas.Filtered.EBpp_AdjustPANCAN_IlluminaHiSeq_RNASeqV2_genExp_filtered` 
where Symbol="BTLA" and ParticipantBarcode="TCGA-ZU-A8S4" and SampleTypeLetterCode="TP"
LIMIT 1000
```
gives 4.4871

**Comment by vthorsson** [comment]
Might be related to doubled rows in `im_expr_df` (thought to have been addressed earlier)
```
> filter(im_expr_df,ParticipantBarcode=="TCGA-ZU-A8S4",Symbol=="BTLA")
# A tibble: 2 x 3
  ParticipantBarcode Symbol normalized_count
  <chr>              <chr>             <dbl>
1 TCGA-ZU-A8S4       BTLA               8.69
2 TCGA-ZU-A8S4       BTLA               4.49
```
The value 8.69 differs from 6.59 above, however.

**Comment by Gibbsdavidl** [comment]
> (8.69+4.49)/2
[1] 6.59

**Comment by vthorsson** [comment]
A looks like this was addressed already 
https://github.com/CRI-iAtlas/shiny-iatlas/issues/143
File did maybe not make it in.

@heimannch , would you be able to double check if the corrected `im_expr_df` solves this?

**Comment by heimannch** [comment]
Yes, the gene expression data from issue #143 matches the gene expression data from file "GenExp_All_CKine_genes.tsv", from the cytokine-network-dev repo. 
I will update the data for the cytokine network module - @andrewelamb do you want me to update this in the repo too?

**Comment by heimannch** [comment]
I just took a closer look, and there are still doubled rows in the file attached in #143 - but at least one of the occurrences is equal to the one in the file "GenExp_All_CKine_genes.tsv".

**Comment by vthorsson** [comment]
Oh, drat! Thanks @heimannch . There should not be double rows at all. I will take a look.

**Comment by heimannch** [comment]
I compiled the whole list of duplicated rows in the ``im_expr_df.feather.gz`` file from issue #143 

The example query in the original issue is still with a problem:
```
> filter(expr_data2,ParticipantBarcode=="TCGA-BH-A1FC",Symbol=="IL13")
# A tibble: 2 x 3
  ParticipantBarcode Symbol normalized_count
  <chr>              <chr>             <dbl>
1 TCGA-BH-A1FC       IL13              0.588
2 TCGA-BH-A1FC       IL13              6.51 
```

We also have some cases with three normalized counts, for example:

``` 
>filter(expr_data2, Symbol == "BTLA", ParticipantBarcode == "TCGA-06-0211")
# A tibble: 3 x 3
  ParticipantBarcode Symbol normalized_count
  <chr>              <chr>             <dbl>
1 TCGA-06-0211       BTLA               2.00
2 TCGA-06-0211       BTLA               3.63
3 TCGA-06-0211       BTLA               5.34
```


[dupl_im_expr.csv.gz](https://github.com/CRI-iAtlas/shiny-iatlas/files/3810834/dupl_im_expr.csv.gz)

**Comment by vthorsson** [comment]
Thanks, makes me think I uploaded the wrong file. Will look

**Comment by vthorsson** [comment]
@heimannch , can this be closed now?

**Comment by heimannch** [comment]
Sure!
